import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import GlobalStyles from "../components/GlobalStyles";
// import { graphql } from "../generated/gql";

export interface TestProps {}

// const AllUser : any = graphql();

const Test = () => {
    
    // const { data } = useQuery( gql`
    //     query () {
    //         users() {
    //             id
    //             username
    //         }
    //     }
    // ` )

    return (
        <>
            <Head>
                <title>Test - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <GlobalStyles>
                    
                    {/* {!!data && <p>{JSON.stringify(data)}</p>} */}

                </GlobalStyles>
            </main>
        </>
    );
};

export default Test;
