import Head from "next/head";
import GlobalStyles from "../components/GlobalStyles";

export interface TestProps {}

const Test = () => {
    return (
        <>
            <Head>
                <title>Test - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <GlobalStyles>Test</GlobalStyles>
            </main>
        </>
    );
};

export default Test;
